// Catálogo de servicios odontológicos sugeridos para autocompletado.
// Lista no exhaustiva: el usuario puede seleccionar uno o escribir el suyo.
// Se mantiene plana (sin grupos) para integrarse con <datalist> nativo.

const DEFAULT_DENTAL_SERVICES = [
  // ── Diagnóstico, consulta y estudios ────────────────────────────────
  'Consulta de valoración',
  'Consulta de primera vez',
  'Consulta de seguimiento',
  'Consulta de control',
  'Consulta de urgencia',
  'Consulta a domicilio',
  'Teleconsulta',
  'Interconsulta',
  'Segunda opinión',
  'Revisión odontológica',
  'Revisión semestral',
  'Revisión anual',
  'Diagnóstico clínico',
  'Plan de tratamiento',
  'Presupuesto de tratamiento',
  'Examen periodontal completo',
  'Examen oclusal',
  'Examen de articulación temporomandibular',
  'Test de vitalidad pulpar',
  'Detección de caries',
  'Detección de cáncer oral',
  'Modelos de estudio',
  'Impresiones de estudio',
  'Impresiones digitales',
  'Escaneo intraoral 3D',
  'Fotografías clínicas',
  'Análisis cefalométrico',
  'Análisis funcional',

  // ── Radiografías e imagenología ─────────────────────────────────────
  'Radiografía periapical',
  'Radiografía panorámica',
  'Radiografía oclusal',
  'Radiografía aleta de mordida',
  'Radiografía lateral de cráneo',
  'Telerradiografía',
  'Serie radiográfica completa',
  'Tomografía dental (CBCT)',
  'Tomografía maxilar',
  'Tomografía mandibular',
  'Diagnóstico por imagen',

  // ── Preventiva y profilaxis ─────────────────────────────────────────
  'Limpieza dental',
  'Limpieza dental profunda',
  'Profilaxis dental',
  'Profilaxis con ultrasonido',
  'Profilaxis con airflow',
  'Detartraje',
  'Eliminación de sarro',
  'Eliminación de placa',
  'Eliminación de manchas',
  'Pulido dental',
  'Aplicación de flúor',
  'Aplicación de barniz de flúor',
  'Aplicación de gel de flúor',
  'Sellador de fosetas y fisuras',
  'Enseñanza de técnica de cepillado',
  'Control de placa bacteriana',
  'Asesoría en salud bucal',
  'Asesoría nutricional',
  'Tratamiento de halitosis',
  'Tratamiento de sensibilidad dental',

  // ── Operatoria / restauradora ───────────────────────────────────────
  'Resina simple',
  'Resina compuesta',
  'Resina estética',
  'Resina fotopolimerizable',
  'Resina nanohíbrida',
  'Resina microhíbrida',
  'Resina de alta estética',
  'Resina en diente anterior',
  'Resina en diente posterior',
  'Resina en incisivo',
  'Resina en canino',
  'Resina en premolar',
  'Resina en molar',
  'Amalgama dental',
  'Cambio de amalgama por resina',
  'Recambio de restauración',
  'Restauración temporal',
  'Restauración provisional',
  'Ionómero de vidrio',
  'Onlay',
  'Inlay',
  'Overlay',
  'Incrustación de resina',
  'Incrustación de porcelana',
  'Incrustación de zirconio',
  'Incrustación de disilicato de litio',
  'Reconstrucción dental',
  'Reconstrucción con poste',
  'Reconstrucción anterior',
  'Reconstrucción posterior',
  'Sellado de resina',
  'Pulido de restauración',

  // ── Endodoncia ──────────────────────────────────────────────────────
  'Endodoncia unirradicular',
  'Endodoncia birradicular',
  'Endodoncia multirradicular',
  'Endodoncia en diente anterior',
  'Endodoncia en premolar',
  'Endodoncia en molar',
  'Endodoncia en pieza temporal',
  'Endodoncia en pieza permanente',
  'Retratamiento endodóntico',
  'Apertura cameral',
  'Preparación biomecánica',
  'Obturación de conductos',
  'Desobturación de conductos',
  'Recubrimiento pulpar directo',
  'Recubrimiento pulpar indirecto',
  'Pulpotomía',
  'Pulpectomía',
  'Apicectomía',
  'Apexificación',
  'Apexogénesis',
  'Microcirugía endodóntica',
  'Hemisección radicular',
  'Tratamiento de absceso periapical',
  'Poste de fibra de vidrio',
  'Poste colado',
  'Núcleo colado',

  // ── Cirugía oral y maxilofacial ─────────────────────────────────────
  'Extracción simple',
  'Extracción quirúrgica',
  'Extracción de tercer molar',
  'Extracción de muela del juicio',
  'Extracción de cordal',
  'Extracción de molar',
  'Extracción de premolar',
  'Extracción de canino',
  'Extracción de incisivo',
  'Extracción de diente temporal',
  'Extracción con osteotomía',
  'Extracción de diente retenido',
  'Extracción de raíz residual',
  'Odontectomía',
  'Germectomía',
  'Cirugía de cordales',
  'Cirugía periapical',
  'Alveoloplastía',
  'Frenectomía',
  'Frenilectomía lingual',
  'Frenilectomía labial',
  'Biopsia oral',
  'Drenaje de absceso',
  'Quistectomía',
  'Tumorectomía',
  'Exéresis de mucocele',
  'Exéresis de ránula',
  'Exéresis de torus palatino',
  'Exéresis de torus mandibular',
  'Cirugía preprotésica',
  'Vestibuloplastía',
  'Reducción de tuberosidad',
  'Sutura',
  'Retiro de puntos',

  // ── Prótesis fija ───────────────────────────────────────────────────
  'Corona de porcelana',
  'Corona metal-porcelana',
  'Corona libre de metal',
  'Corona de zirconio',
  'Corona de disilicato de litio',
  'Corona de e.max',
  'Corona de oro',
  'Corona de níquel-cromo',
  'Corona provisional',
  'Corona temporal',
  'Corona definitiva',
  'Corona estética',
  'Corona sobre poste',
  'Carilla de porcelana',
  'Carilla de cerámica',
  'Carilla de resina',
  'Carilla de composite',
  'Carilla de disilicato de litio',
  'Carilla directa',
  'Carilla indirecta',
  'Carilla mínimamente invasiva',
  'Lumineers',
  'Puente fijo (por pieza)',
  'Puente Maryland',
  'Puente cantilever',
  'Puente convencional',
  'Recementado de corona',
  'Recementado de puente',
  'Reparación de corona',

  // ── Prótesis removible ──────────────────────────────────────────────
  'Prótesis total',
  'Prótesis total superior',
  'Prótesis total inferior',
  'Prótesis parcial removible',
  'Prótesis parcial acrílica',
  'Prótesis parcial cromo-cobalto',
  'Prótesis flexible',
  'Prótesis inmediata',
  'Prótesis temporal',
  'Prótesis provisional',
  'Sobredentadura',
  'Reparación de prótesis',
  'Rebase de prótesis',
  'Forrado de prótesis',
  'Almohadillado de prótesis',
  'Acondicionador de tejidos',
  'Ajuste de prótesis',
  'Limpieza de prótesis',
  'Mantenimiento de prótesis',

  // ── Implantología ───────────────────────────────────────────────────
  'Implante dental',
  'Implante unitario',
  'Implante múltiple',
  'Implante inmediato',
  'Implante diferido',
  'Mini implante',
  'Implante cigomático',
  'Pilar de implante',
  'Tornillo de cicatrización',
  'Corona sobre implante',
  'Provisional sobre implante',
  'Prótesis sobre implantes',
  'Prótesis híbrida',
  'Prótesis fija sobre implantes',
  'Carga inmediata',
  'Carga temprana',
  'Carga diferida',
  'All-on-4',
  'All-on-6',
  'Cirugía guiada para implantes',
  'Injerto óseo',
  'Injerto de hueso autólogo',
  'Injerto de hueso sintético',
  'Injerto particulado',
  'Bloque de hueso',
  'Regeneración ósea guiada',
  'Preservación alveolar',
  'Expansión ósea',
  'Elevación de seno maxilar',
  'Sinus lift abierto',
  'Sinus lift cerrado',
  'PRGF / PRF',
  'Membrana de colágeno',
  'Membrana reabsorbible',
  'Membrana no reabsorbible',
  'Mantenimiento de implante',

  // ── Ortodoncia ──────────────────────────────────────────────────────
  'Consulta de ortodoncia',
  'Estudio de ortodoncia',
  'Diagnóstico ortodóntico',
  'Ortodoncia interceptiva',
  'Ortodoncia preventiva',
  'Ortodoncia funcional',
  'Ortodoncia correctiva',
  'Ortodoncia lingual',
  'Ortodoncia adulta',
  'Ortodoncia infantil',
  'Brackets metálicos',
  'Brackets estéticos',
  'Brackets de zafiro',
  'Brackets cerámicos',
  'Brackets de autoligado',
  'Cementado de brackets',
  'Recementado de bracket',
  'Reposición de bracket',
  'Cambio de arcos',
  'Cambio de ligaduras',
  'Ligaduras elásticas',
  'Ligaduras metálicas',
  'Ajuste mensual de ortodoncia',
  'Cita de emergencia ortodóntica',
  'Retiro de brackets',
  'Alineadores invisibles',
  'Invisalign',
  'Spark aligners',
  'Pegado de attachment',
  'IPR (stripping)',
  'Microimplante ortodóntico',
  'Mini-tornillo ortodóntico',
  'Disyunción palatina',
  'Expansión maxilar',
  'Quad helix',
  'Lip bumper',
  'Arco lingual',
  'Arco palatino',
  'Botón de Nance',
  'Aparato funcional',
  'Aparato de Frankel',
  'Aparato bionator',
  'Activador',
  'Twin block',
  'Máscara facial',
  'Mentonera',
  'Headgear',
  'Plano de mordida',
  'Pista directa',
  'Retiro de aparatología',
  'Retenedor fijo',
  'Retenedor removible',
  'Placa Hawley',

  // ── Odontopediatría ─────────────────────────────────────────────────
  'Consulta pediátrica',
  'Profilaxis pediátrica',
  'Adaptación pediátrica',
  'Tratamiento conductual',
  'Resina pediátrica',
  'Restauración pediátrica anterior',
  'Restauración pediátrica posterior',
  'Pulpotomía pediátrica',
  'Pulpotomía con MTA',
  'Pulpotomía con formocresol',
  'Corona de acero cromado',
  'Corona pediátrica estética',
  'Corona de zirconio pediátrica',
  'Sellador pediátrico',
  'Mantenedor de espacio',
  'Espaciador pediátrico',
  'Frenectomía pediátrica',
  'Tratamiento de traumatismo dental',
  'Reposición dental',
  'Ferulización dental',
  'Tratamiento de diente avulsionado',

  // ── Periodoncia ─────────────────────────────────────────────────────
  'Curetaje',
  'Raspado y alisado radicular',
  'Mantenimiento periodontal',
  'Fase higiénica periodontal',
  'Cirugía periodontal',
  'Cirugía resectiva periodontal',
  'Cirugía regenerativa periodontal',
  'Plástica periodontal',
  'Colgajo periodontal',
  'Gingivectomía',
  'Gingivoplastía',
  'Gingivectomía estética',
  'Injerto gingival',
  'Injerto gingival libre',
  'Injerto de tejido conectivo',
  'Cubrimiento radicular',
  'Aumento de encía queratinizada',
  'Alargamiento de corona',
  'Tratamiento de bolsas periodontales',
  'Aplicación de antibiótico local',
  'Irrigación periodontal',

  // ── Estética dental ─────────────────────────────────────────────────
  'Blanqueamiento dental',
  'Blanqueamiento en consultorio',
  'Blanqueamiento en casa',
  'Blanqueamiento con LED',
  'Blanqueamiento con láser',
  'Blanqueamiento interno',
  'Blanqueamiento de diente desvitalizado',
  'Reblanqueamiento',
  'Diseño de sonrisa',
  'Diseño digital de sonrisa (DSD)',
  'Microabrasión del esmalte',
  'Macroabrasión',
  'Bonding estético',
  'Cierre de diastemas',
  'Recontorneado dental',
  'Estética gingival',

  // ── ATM / oclusión / dolor orofacial ────────────────────────────────
  'Diagnóstico de ATM',
  'Tratamiento de ATM',
  'Manipulación de ATM',
  'Guarda oclusal',
  'Placa miorrelajante',
  'Férula de descarga',
  'Férula oclusal blanda',
  'Férula oclusal dura',
  'Férula de relajación',
  'Férula de reposicionamiento',
  'Férula Michigan',
  'Férula NTI',
  'Tratamiento de bruxismo',
  'Ajuste oclusal',
  'Equilibración oclusal',
  'Tallado selectivo',
  'Tratamiento del dolor orofacial',
  'Infiltración articular',

  // ── Estética facial complementaria ──────────────────────────────────
  'Aplicación de toxina botulínica',
  'Bótox en músculos masticatorios',
  'Bótox para bruxismo',
  'Bótox para sonrisa gingival',
  'Rellenos faciales',
  'Ácido hialurónico',
  'Mesoterapia facial',
  'PRP facial',

  // ── Sedación y anestesia ────────────────────────────────────────────
  'Aplicación de anestesia local',
  'Anestesia troncular',
  'Anestesia infiltrativa',
  'Anestésico adicional',
  'Sedación consciente',
  'Sedación inhalatoria',
  'Óxido nitroso',
  'Premedicación',

  // ── Administrativo / documentación / otros ──────────────────────────
  'Cementado',
  'Cita de control',
  'Receta médica',
  'Constancia médica',
  'Justificante médico',
  'Certificado odontológico',
  'Carta de canalización',
  'Pase a especialista',
  'Honorarios profesionales',
  'Material desechable',
  'Kit de blanqueamiento en casa',
  'Cubeta personalizada',
  'Modelo de yeso',
  'Encerado diagnóstico',
  'Mock-up'
];

export default DEFAULT_DENTAL_SERVICES;
